version: "2"

services:
  web:
    container_name: bmat_web
    build:
      dockerfile: build/web/Dockerfile
      context: .
    env_file:
      - deploy/env
      - deploy/web/env
    volumes:
      - web_vol:/home/web/instance
    depends_on:
      - postgres

  postgres:
    container_name: bmat_postgres
    image: postgres
    # env vars will initialize volume if empty; it will allow public connect&co though
    env_file:
      - deploy/env
      - deploy/postgres/env
    volumes:
      - db_vol:/var/lib/postgresql/data

  web_server:
    container_name: bmat_web_server
    build:
      dockerfile: build/web_server/Dockerfile
      context: .
    env_file:
      - deploy/env
      - deploy/web_server/env
    ports:
      - "80:80"
    depends_on:
      - web
    volumes_from:
      - web

volumes:
  db_vol:
    driver: local
  web_vol:
    driver: local
